### PR TITLE
node executable name

### PR DESCRIPTION
**Pull request by erixtekila**

### CODE REVIEW

**Comment by damoebius** [comment]
On my ubuntu, it's nodejs.
What's your OS ?

**Comment by erixtekila** [comment]
on osx, node.
I use ubuntu too, it is node also.

**Comment by damoebius** [comment]
Mince alors c,est pas bon.
Il faut tester d'abord si nodejs existe et sinon utiliser node

**Comment by dmouton** [comment]
Could you try this for me :

SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )
NODE_CMD=nodejs
command -v ${NODE_CMD} >/dev/null 2>&1 || NODE_CMD=node
${NODE_CMD} ${SCRIPTPATH}/haxe-cli.js $*

**Comment by erixtekila** [comment]
That does the trick ! Thanks.

**Comment by damoebius** [comment]
Ok, you can try the new 0.320.10 release on npm

**Pull request closed without merging**
